# Generated by Django 5.0.1 on 2024-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requester',
            field=models.TextField(blank=True, null=True),
        ),
    ]
